# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-20 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim Soyisim')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=3000, verbose_name='Mesajınız')),
                ('sending_date', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
            ],
        ),
    ]
